---
name: Feature request
description: Suggest an idea for this project
labels:
  - feature request

body:

  - type: dropdown
    id: environment
    attributes:
      label: What environment are you running?
      options:
        - Self Hosted
        - "Hosted (https://app.invoicing.co)"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Invoice Ninja version
      description: Enter the complete Invoice Ninja version you are currently using.
      placeholder: v5.13.31
    validations:
      required: true

  - type: checkboxes
    id: existing-requests
    attributes:
      label: Have you searched existing issues and requests?
      options:
        - label: I have searched existing issues and requests.
          required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your request or question.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the request or question here.