<?php
/*
 * @OA\Schema(
 *   schema="ClientContact",
 *   type="object",
 *       @OA\Property(property="id", type="string", example="Opnel5aKBz", description="_________"),
 *       @OA\Property(property="user_id", type="string", example="", description="__________"),
 *       @OA\Property(property="company_id", type="string", example="", description="________"),
 *       @OA\Property(property="client_id", type="string", example="", description="________"),
 *       @OA\Property(property="first_name", type="string", example="", description="________"),
 *       @OA\Property(property="last_name", type="string", example="", description="________"),
 *       @OA\Property(property="phone", type="string", example="", description="________"),
 *       @OA\Property(property="custom_value1", type="string", example="", description="________"),
 *       @OA\Property(property="custom_value2", type="string", example="", description="________"),
 *       @OA\Property(property="custom_value3", type="string", example="", description="________"),
 *       @OA\Property(property="custom_value4", type="string", example="", description="________"),
 *       @OA\Property(property="email", type="string", example="", description="________"),
 *       @OA\Property(property="accepted_terms_version", type="string", example="", description="________"),
 *       @OA\Property(property="password", type="string", example="", description="________"),
 *       @OA\Property(property="confirmation-code", type="string", example="", description="________"),
 *       @OA\Property(property="token", type="string", example="", description="________"),
 *       @OA\Property(property="is_primary", type="boolean", example=true, description="________"),
 *       @OA\Property(property="confirmed", type="boolean", example=true, description="________"),
 *       @OA\Property(property="is_locked", type="boolean", example=true, description="________"),
 *       @OA\Property(property="send_email", type="boolean", example=true, description="________"),
 *       @OA\Property(property="failed_logins", type="number", format="integer", example="3", description="________"),
 *       @OA\Property(property="email_verified_at", type="number", format="integer", example="134341234234", description="________"),
 *       @OA\Property(property="paid_to_date", type="number", format="float", example="10.00", description="________"),
 *       @OA\Property(property="last_login", type="number", format="integer", example="134341234234", description="Timestamp"),
 *       @OA\Property(property="created_at", type="number", format="integer", example="134341234234", description="Timestamp"),
 *       @OA\Property(property="updated_at", type="number", format="integer", example="134341234234", description="Timestamp"),
 *       @OA\Property(property="deleted_at", type="number", format="integer", example="134341234234", description="Timestamp"),
 * )
 */
