<?php
/**
 * @OA\Schema(
 *   schema="RecurringExpense",
 *   type="object",
 *       @OA\Property(property="id", type="string", example="Opnel5aKBz", description="_________"),
 *       @OA\Property(property="user_id", type="string", example="", description="__________"),
 *       @OA\Property(property="assigned_user_id", type="string", example="", description="__________"),
 *       @OA\Property(property="company_id", type="string", example="", description="________"),
 *       @OA\Property(property="client_id", type="string", example="", description="________"),
 *       @OA\Property(property="invoice_id", type="string", example="", description="________"),
 *       @OA\Property(property="bank_id", type="string", example="", description="________"),
 *       @OA\Property(property="invoice_currency_id", type="string", example="", description="________"),
 *       @OA\Property(property="expense_currency_id", type="string", example="", description="________"),
 *       @OA\Property(property="invoice_category_id", type="string", example="", description="________"),
 *       @OA\Property(property="payment_type_id", type="string", example="", description="________"),
 *       @OA\Property(property="recurring_expense_id", type="string", example="", description="________"),
 *       @OA\Property(property="private_notes", type="string", example="", description="________"),
 *       @OA\Property(property="public_notes", type="string", example="", description="________"),
 *       @OA\Property(property="transaction_reference", type="string", example="", description="________"),
 *       @OA\Property(property="transcation_id", type="string", example="", description="________"),
 *       @OA\Property(property="custom_value1", type="string", example="", description="________"),
 *       @OA\Property(property="custom_value2", type="string", example="", description="________"),
 *       @OA\Property(property="custom_value3", type="string", example="", description="________"),
 *       @OA\Property(property="custom_value4", type="string", example="", description="________"),
 *       @OA\Property(property="tax_name1", type="string", example="", description="________"),
 *       @OA\Property(property="tax_name2", type="string", example="", description="________"),
 *       @OA\Property(property="tax_rate1", type="number", format="float", example="10.00", description="_________"),
 *       @OA\Property(property="tax_rate2", type="number", format="float", example="10.00", description="_________"),
 *       @OA\Property(property="tax_name3", type="string", example="", description="________"),
 *       @OA\Property(property="tax_rate3", type="number", format="float", example="10.00", description="_________"),
 *       @OA\Property(property="amount", type="number", format="float", example="10.00", description="_________"),
 *       @OA\Property(property="frequency_id", type="number", format="int", example="1", description="_________"),
 *       @OA\Property(property="remaining_cycles", type="number", format="int", example="1", description="_________"),
 *       @OA\Property(property="foreign_amount", type="number", format="float", example="10.00", description="_________"),
 *       @OA\Property(property="exchange_rate", type="number", format="float", example="0.80", description="_________"),
 *       @OA\Property(property="date", type="string", example="", description="________"),
 *       @OA\Property(property="payment_date", type="string", example="", description="________"),
 *       @OA\Property(property="should_be_invoiced", type="boolean", example=true, description="_________"),
 *       @OA\Property(property="is_deleted", type="boolean", example=true, description="_________"),
 *       @OA\Property(property="last_sent_date", type="string", format="date", example="1994-07-30", description="The Date it was sent last"),
 *       @OA\Property(property="next_send_date", type="string", format="date", example="1994-07-30", description="The next send date"),
 *       @OA\Property(property="invoice_documents", type="boolean", example=true, description=""),
 *       @OA\Property(property="updated_at", type="number", format="integer", example="1434342123", description="Timestamp"),
 *       @OA\Property(property="archived_at", type="number", format="integer", example="1434342123", description="Timestamp"),
 * )
 */
