<?php
/**
 * @OA\Schema(
 *   schema="Task",
 *   type="object",
 *       @OA\Property(property="id", type="string", example="Opnel5aKBz", description="_________"),
 *       @OA\Property(property="user_id", type="string", example="", description="__________"),
 *       @OA\Property(property="assigned_user_id", type="string", example="", description="__________"),
 *       @OA\Property(property="company_id", type="string", example="", description="________"),
 *       @OA\Property(property="client_id", type="string", example="", description="________"),
 *       @OA\Property(property="invoice_id", type="string", example="", description="________"),
 *       @OA\Property(property="project_id", type="string", example="", description="________"),
 *       @OA\Property(property="number", type="string", example="", description="________"),
 *       @OA\Property(property="time_log", type="string", example="", description="________"),
 *       @OA\Property(property="start_time", type="integer", example="", description="________"),
 *       @OA\Property(property="is_running", type="boolean", example=true, description="________"),
 *       @OA\Property(property="is_deleted", type="boolean", example=true, description="________"),
 *       @OA\Property(property="task_status_id", type="string", example="", description="________"),
 *       @OA\Property(property="description", type="string", example="", description="________"),
 *       @OA\Property(property="duration", type="integer", example="", description="________"),
 *       @OA\Property(property="task_status_sort_order", type="integer", example="", description="________"),
 *       @OA\Property(property="custom_value1", type="string", example="", description="________"),
 *       @OA\Property(property="custom_value2", type="string", example="", description="________"),
 *       @OA\Property(property="custom_value3", type="string", example="", description="________"),
 *       @OA\Property(property="custom_value4", type="string", example="", description="________"),
 *       @OA\Property(property="created_at", type="number", format="integer", example="1434342123", description="Timestamp"),
 *       @OA\Property(property="updated_at", type="number", format="integer", example="1434342123", description="Timestamp"),
 *       @OA\Property(property="archived_at", type="number", format="integer", example="1434342123", description="Timestamp"),
 * )
 */
